# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e112ec41d5db705f0fdc434cfcbbce4cc4ef71d918c0e27cc7bb98358900e48c2c1e9e2da6c5cb2e10742b80863454d2ed4b5dcdd1bf8f8ee2ee757a483eb71

test:
  secret_key_base: df7988671b743f79073ef8a10de8c7ff84f9450361b4beb79112eb8f5b28aeb7b436dc87ba1e091c0c1a5f0525730fa0fa8149881d32aa0a2c14c43dce075e5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
